### ISSUE TITLE
Errors on vagrant up

### ISSUE THREAD

**Issue by adunstan** [manuelnaranjo/vagrant-openproject#2]
==> default: Fetching https://github.com/opf/openproject-plugins.git
==> default: Fetching https://github.com/finnlabs/openproject-meeting.git
==> default: fatal: ambiguous argument 'stable': unknown revision or path not in the working tree.
==> default: Use '--' to separate paths from revisions
==> default: Retrying git rev-parse stable due to error (2/3): Bundler::Source::Git::GitCommandError Git error: command `git rev-parse stable` in directory /opt/openproject/vendor/ruby-2.1.1/lib/ruby/gems/2.1.0/cache/bundler/git/openproject-meeting-d20381f837e160805983c70eb944d49c32e4976f has failed.
==> default: If this error persists you could try removing the cache directory '/opt/openproject/vendor/ruby-2.1.1/lib/ruby/gems/2.1.0/cache/bundler/git/openproject-meeting-d20381f837e160805983c70eb944d49c32e4976f'
==> default: fatal: ambiguous argument 'stable': unknown revision or path not in the working tree.
==> default: Use '--' to separate paths from revisions
==> default: Retrying git rev-parse stable due to error (3/3): Bundler::Source::Git::GitCommandError Git error: command `git rev-parse stable` in directory /opt/openproject/vendor/ruby-2.1.1/lib/ruby/gems/2.1.0/cache/bundler/git/openproject-meeting-d20381f837e160805983c70eb944d49c32e4976f has failed.
==> default: If this error persists you could try removing the cache directory '/opt/openproject/vendor/ruby-2.1.1/lib/ruby/gems/2.1.0/cache/bundler/git/openproject-meeting-d20381f837e160805983c70eb944d49c32e4976f'
==> default: fatal: ambiguous argument 'stable': unknown revision or path not in the working tree.
==> default: Use '--' to separate paths from revisions
==> default: Git error: command `git rev-parse stable` in directory
==> default: /opt/openproject/vendor/ruby-2.1.1/lib/ruby/gems/2.1.0/cache/bundler/git/openproject-meeting-d20381f837e160805983c70eb944d49c32e4976f
==> default: has failed.
==> default: If this error persists you could try removing the cache directory
==> default: '/opt/openproject/vendor/ruby-2.1.1/lib/ruby/gems/2.1.0/cache/bundler/git/openproject-meeting-d20381f837e160805983c70eb944d49c32e4976f'
==> default: /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git/git_proxy.rb:154:in `allowed_in_path'
==> default: : 
==> default: The git source https://github.com/opf/openproject-plugins.git is not yet checked out. Please run`bundle install`before trying to start your application
==> default:  (
==> default: Bundler::GitError
==> default: )
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git/git_proxy.rb:45:in`revision'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git.rb:267:in `revision'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git.rb:81:in`install_path'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/path.rb:112:in `load_spec_files'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git.rb:176:in`load_spec_files'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/path.rb:86:in `local_specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git.rb:150:in`specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:522:in `block in converge_locked_specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:511:in`each'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:511:in `converge_locked_specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:191:in`resolve'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:133:in `specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:178:in`specs_for'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:167:in `requested_specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/environment.rb:18:in`requested_specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/runtime.rb:13:in `setup'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler.rb:119:in`setup'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/setup.rb:17:in `<top (required)>'
==> default:    from /opt/openproject/vendor/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'
==> default:    from /opt/openproject/vendor/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
==> default: /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git/git_proxy.rb:154:in`allowed_in_path'
==> default: : 
==> default: The git source https://github.com/opf/openproject-plugins.git is not yet checked out. Please run `bundle install` before trying to start your application
==> default:  (
==> default: Bundler::GitError
==> default: )
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git/git_proxy.rb:45:in `revision'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git.rb:267:in`revision'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git.rb:81:in `install_path'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/path.rb:112:in`load_spec_files'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git.rb:176:in `load_spec_files'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/path.rb:86:in`local_specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/source/git.rb:150:in `specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:522:in`block in converge_locked_specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:511:in `each'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:511:in`converge_locked_specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:191:in `resolve'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:133:in`specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:178:in `specs_for'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/definition.rb:167:in`requested_specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/environment.rb:18:in `requested_specs'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/runtime.rb:13:in`setup'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler.rb:119:in `setup'
==> default:    from /opt/openproject/vendor/bundle/ruby/2.1.0/gems/bundler-1.5.2/lib/bundler/setup.rb:17:in`<top (required)>'
==> default:    from /opt/openproject/vendor/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in `require'
==> default:    from /opt/openproject/vendor/ruby-2.1.1/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:55:in`require'

**Comment by manuelnaranjo** [comment]
Feel free to fork and fix the project, I'm not using it at all right now, and can't work on it either sorry.
